server:
  port: 8081

spring:
  flyway:
    enabled: true
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

mybatis:
  #TODO:定义mapper xml的位置
  mapper-locations: classpath:indi/daniel/fling/springboot/datasource/mybatis/mapper/*.xml
  type-aliases-package: indi.daniel.fling.springboot.datasource.mybatis.entity
  type-handlers-package: indi.daniel.fling.springboot.datasource.mybatis.dataconverter