server:
  port: 8081

spring:
  flyway:
    enabled: true
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

mybatis:
  #TODO:定义mapper xml的位置，暂时没有解决方案
#  mapper-locations:
#    - classpath:indi/daniel/fling/springboot/datasource/mybatis/mapper/UserDao.xml
  type-aliases-package: indi.daniel.fling.springboot.datasoure.mybatis.entity
  type-handlers-package: indi.daniel.fling.springboot.datasoure.mybatis.dataconverter