shiro:
  successUrl: /index # 用户登录成功
  loginUrl: /401       # 用户未登录时跳转的请求路径
  unauthorizedUrl: /403    # 用户没有访问权限时跳转的请求路径
  userNativeSessionManager: true
  sessionManager:
    cookie:
      name: MYSHIRO

